name: Run Unit and Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Change the version to 18

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm run test:unit

  integration_tests:
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Change the version to 18

    - name: Install dependencies
      run: npm install

    - name: Run integration tests
      run: npm run test:integration
